package model

import (
	"encoding/json"
	"time"
)

type VideoStatus string

const (
	StatusPending    VideoStatus = "pending"
	StatusProcessing VideoStatus = "processing"
	StatusReady      VideoStatus = "ready"
	StatusFailed     VideoStatus = "failed"
)

type Video struct {
	ID                string          `json:"id"`
	Status            VideoStatus     `json:"status"`
	Progress          int             `json:"progress"`
	OriginalPath      string          `json:"-"`
	Duration          *float64        `json:"duration,omitempty"`
	Width             *int            `json:"width,omitempty"`
	Height            *int            `json:"height,omitempty"`
	SizeBytes         int64           `json:"size_bytes"`
	ErrorMessage      *string         `json:"error_message,omitempty"`
	Segments          json.RawMessage `json:"segments,omitempty"`
	AudioTracksRaw    json.RawMessage `json:"-"`
	SubtitleTracksRaw json.RawMessage `json:"-"`
	StoryboardRaw     json.RawMessage `json:"-"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
}

// Track describes an extracted audio or subtitle track as stored in the
// audio_tracks / subtitle_tracks JSONB columns.
type Track struct {
	Index    int    `json:"index"`
	Language string `json:"language,omitempty"`
	Title    string `json:"title,omitempty"`
}

// Storyboard describes the preview sprite generated by the transcoder, stored
// in the storyboard JSONB column. The API derives scrubbing cues from it, so
// coordinates always match the actual sprite regardless of worker settings.
type Storyboard struct {
	IntervalSeconds int `json:"interval_seconds"`
	TileWidth       int `json:"tile_width"`
	TileHeight      int `json:"tile_height"`
	Columns         int `json:"columns"`
	TileCount       int `json:"tile_count"`
}
