name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [api, transcoder]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: ${{ matrix.module }}/go.mod

      - name: Build
        working-directory: ${{ matrix.module }}
        run: go build -v ./...

      - name: Test
        working-directory: ${{ matrix.module }}
        run: go test -v ./...
